### ISSUE TITLE
Nicer way to remove a component from all entities?

### ISSUE THREAD

**Issue by deifactor** [Ralith/hecs#116]
A pattern I have in my game's codebase is that one system will create a bunch of components attached to entities, and then another system will process them all and clear them. Currently, I'm calling iterating over `world.query_mut::<MyComponent>()` and calling `world.remove_one` on each one, but I'm not sure if that's the fastest possible way. Even if there's no speed-up to be gained, a `world.remove_all::<MyComponent>()` might be nice purely for ergonomics.

**Comment by Ralith** [comment]
Could your application replace insertion/removal of components with accumulation of an external `Vec<Entity>` or `Vec<(Entity, T)>` which it later drains? That might improve performance more than any API extension, because it avoids moving entities between archetypes.

**Comment by deifactor** [comment]
That could also work, yeah. I'm using it to mark 'here are the entities that will receive damage', so I could just make a `Vec<(Entity, Damage)>` and share that around.

I'm converting from specs, since that's what my game used to use, and the attach/clear paradigm is what the tutorial I was using also used. Looking into it, I think that is in fact more efficient in specs than in legion/hecs. So if you think this is sufficiently against the archetype paradigm, I'm fine with just not implementing this. Up to you :)

**Comment by Ralith** [comment]
I prefer not to extend the API unless the benefit of an extension for a concrete use case is significantly larger than the maintenance cost. Since it sounds like the `Vec` solution will be better for you, I think this lacks sufficient motivation. Feel free to reopen if a compelling use case arises, and thanks for the discussion!

**Comment by deifactor** [comment]
Actually, if I can ask a quick question:

I'm going to be modeling poison and other such debuffs at some point. The specs-y way to do it would be to have a PoisonComponent with an amount and a duration, have a PoisonSystem iterate over that, and enqueue damage instances, removing it when the poison finishes. This has the same performance issues, though less so since things becoming poisoned/cured is rarer than them registering a move/attack intent. And in any case, this is a turn-based game, so performance of the game logic isn't super critical.

But I'm curious what the archetype-y way would be. Have a StatusComponent with a vector of status ailments (or a bunch of fields) for each entity that can be buffed/debuffed? Have each debuff be its own entity?

**Comment by Ralith** [comment]
Transient components are fine so long as they're not being added/removed en masse. You could instead use something like an [`IndexSet`](https://docs.rs/indexmap/1.6.0/indexmap/set/struct.IndexSet.html) to track groups of entities on the side, but I don't think there's a benefit, even ignoring the costs of complicating your code.
