### ISSUE TITLE
Deprecate World::get(_mut) in favor of World::query_one

### ISSUE THREAD

**Issue by Ralith** [Ralith/hecs#121]
These are, in theory, redundant; both expose access to a single entity's components, but query_one is significantly more versatile. We should verify that they have similar performance, optimize if necessary, then deprecate for at least one major release cycle before removing entirely.

**Comment by Ralith** [comment]
This also falls under #143.

**Comment by Ralith** [comment]
Same story for `EntityRef::get` vs. `EntityRef::query`.

**Comment by Ralith** [comment]
@PsichiX points out that this suggests the removal of `get_unchecked`, which would imply adding a `query_one_unchecked`, which seems reasonable to have. Future work could even extend that to `query_unchecked`, allowing external schedulers to bypass dynamic checks.

**Comment by PsichiX** [comment]
i'll have to check what i could gain from `query_unchecked` for my scheduler/pipelines and give some thoughts on that.

**Comment by Ralith** [comment]
On review I'm second-guessing the ergonomics of this. `get` doesn't require an intermediate variable to hold the query, because a single component can be ergonomically exposed via a smart pointer. You can't destructure a temporary smart pointer, so AFAICT there's no way to get `let x: &Component = world.query_one::<&Component>(e)?`.
