### ISSUE TITLE
reserve_entity does not increment entities.len() when flushed

### ISSUE THREAD

**Issue by cart** [Ralith/hecs#133]
Repro:

```rust
#[test]
fn test() {
    let mut e = Entities::default();
    let e1 = e.reserve_entity();
    e.flush(|x, y| {});
    // this fails
    assert_eq!(e.len(), 1);
}
```

This causes "subtract with overflow" errors when despawning a reserved entity (after flushing).

```rust
#[test]
fn reserve_test() {
    let mut world = World::new();
    let entity = world.reserve_entity();
    world.flush();
    world.despawn(entity).unwrap();
}
```

This effectively makes entity reservation useless (unless the entities are never despawed). I'm experimenting with using the new hecs entity allocator in bevy, which is what surfaced this.

Introduced by #86

@Ralith  @mjhostet

**Comment by Ralith** [comment]
Good catch, thanks! Fix drafted for review.

**Comment by cart** [comment]
Awesome! Yeah the fix works on my end!
