### ISSUE TITLE
NoSuchEntity -> https://doc.rust-lang.org/std/option/struct.NoneError.html

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Ralith/hecs#169]

**Comment by Ralith** [comment]
Thanks for your interest! I don't think this would be an improvement, because `std::option::NoneError` is specific to `Option`, and `NoSuchEntity` is much more self-explanatory.

**Comment by dzmitry-lahoda** [comment]
may be at least impl into NoneError ?

**Comment by dzmitry-lahoda** [comment]
@Ralith would you accept patch for NoSuchEntity -> into  NoneError?

**Comment by dzmitry-lahoda** [comment]
impl Into<NonError> for NoSuchEntity

**Comment by Ralith** [comment]
Can you give an example of where this would be useful? Have you considered using [`Result::ok`](https://doc.rust-lang.org/std/result/enum.Result.html#method.ok) to convert to `Option` explicitly?
