### ISSUE TITLE
Query a slice of entities

### ISSUE THREAD

**Issue by gzp-crey** [Ralith/hecs#170]
As I see query can be executed only on the entire world. I have a set (slice) of entities and I'd like to perform the query on this slice somehow. Is it possible ?
I could perform the query on the world and check if the entity is in the slice, but that requires a search for each entity in the slice.
Also I could iterate over the slice and fetch the component from the world and check for the required component, but it requires handcrafted solution for each case (ex using query_one)
Is there any other option, or is it possible to add such an interface to to library?
```
impl World {
    fn query_slice<Q:Query>(slice: &[Entity]) -> QuerySliceBorrow  {...}
}
```

Some use case, where order matters: Some entities are part of a graph and I keep a sorted vector for the update order, thus iteration should happen in the order of the slice, instead of the default ordering.

**Comment by Ralith** [comment]
[`World::query_one`](https://docs.rs/hecs/0.5.2/hecs/struct.World.html#method.query_one) is intended to address the case where you want to run a query against a specific entity. Can you iterate over your slice and use that?

**Comment by gzp-crey** [comment]
Yes, actually it turned out to be simpler as I expected, thus no need to any extension.
Thanks for the great lib.

**Comment by Ralith** [comment]
Great!
