### ISSUE TITLE
Provide some sort of data structure for resources

### ISSUE THREAD

**Issue by FeldrinH** [Ralith/hecs#173]
It would be nice to have some sort of data structure for easily storing and passing around shared resources, similar to for example https://docs.rs/legion/0.4.0/legion/struct.Resources.html

**Comment by Ralith** [comment]
I recommend using a struct. If you absolutely require dynamic typing for some reason, consider the [resources](https://crates.io/crates/resources) crate. I'm not aware of any upside to baking something like that into hecs.

**Comment by FeldrinH** [comment]
The resources crate seems like a good option for my use case. Would be nice to mention these options in the docs somewhere. The resources crate is kinda hard to find when googling (at least I couldn't find it).
