### ISSUE TITLE
`spawn_batch` reserves exactly the memory it needs no matter how small leading to constant re-allocation when used repeatedly

### ISSUE THREAD

**Issue by Imberflur** [Ralith/hecs#175]
Using `spawn_batch` with 5 items 20,000 times takes ~5 seconds and most time is spent copying data to the reallocated archetype storage:
![image](https://user-images.githubusercontent.com/2002109/126846570-a2bba960-bbed-4705-aa1f-0bfed831ee52.png)
[flamegraph.svg.zip](https://github.com/Ralith/hecs/files/6871429/flamegraph.svg.zip)

`spawn_batch` calls `reserve_inner` with the exact amount of items needed https://github.com/Ralith/hecs/blob/4088845dfe572c9e3534f9f818487685a17b6599/src/world.rs#L187
which then calls reserve on the archetype
https://github.com/Ralith/hecs/blob/4088845dfe572c9e3534f9f818487685a17b6599/src/world.rs#L312
https://github.com/Ralith/hecs/blob/4088845dfe572c9e3534f9f818487685a17b6599/src/archetype.rs#L238-L242

Meanwhile the `Archetype::allocate` function used by `World::spawn` bumps the size by 64 if it reaches the max capacity.
https://github.com/Ralith/hecs/blob/4088845dfe572c9e3534f9f818487685a17b6599/src/archetype.rs#L223-L227

One solution to improve performance here would be to adopt this `64` value as the minimum that `spawn_batch` reserves.

However, I also wonder if it would be better to consider a more aggressive growth strategy like that used by `Vec` to minimize the re-allocation and copying needed.

Also, I'm not sure what has already been considered and/or done here or what the limitations would be in this context, but another idea that could help is breaking the archetype into large chunks to prevent the need for copying everything when growing past the current capacity.

**Comment by Ralith** [comment]
Thanks for the report!

> Meanwhile the Archetype::allocate function used by World::spawn bumps the size by 64 if it reaches the max capacity.

That's not quite accurate. `Archetype::grow` takes the size *increment*, so we bump the capacity by the larger of the current length and 64, i.e. standard exponential resizing.

> another idea that could help is breaking the archetype into large chunks to prevent the need for copying everything when growing past the current capacity.

This is on the table if a need for it is demonstrated, but overkill in this instance.

**Comment by Imberflur** [comment]
> That's not quite accurate. Archetype::grow takes the size increment, so we bump the capacity by the larger of the current length and 64, i.e. standard exponential resizing.
Ah I missed this, thanks for the clarification :slightly_smiling_face:
