### ISSUE TITLE
"Or"/disjunction query combinator

### ISSUE THREAD

**Issue by sdleffler** [Ralith/hecs#191]
Currently `Option` allows you to "try" to fetch a fetchable thing; we just came across an issue where we'd like to be able to match on queries which have one fetchable subset *or* another fetchable subset. I think something like an `Or<Q, P>` combinator that implements `Fetch` would be feasible?

**Comment by Ralith** [comment]
Semantically speaking, it'd be like `(Option<Q>, Option<P>)`, except skipping cases where both are `None`, right? I think that should be pretty straightforward. Probably yielding an enum with cases for either or both.

**Comment by Ralith** [comment]
Of course, you could reduce your query to disjunctive normal form and use separate loops for each conjunction, but it's easy to imagine that might be significantly less ergonomic.

**Comment by sdleffler** [comment]
> 
> 
> Of course, you could reduce your query to disjunctive normal form and use separate loops for each conjunction, but it's easy to imagine that might be significantly less ergonomic.

Yeah, that's what we're currently doing. In our case we actually know that it will be an exclusive or w/ no possible "both" case, so I was imagining an `Either<Q, P>` kind of combinator, tbh. Though I don't know if an XOR style of combinator would want to skip "both" cases...

**Comment by Ralith** [comment]
How's #192 look?

Exclusive OR feels kind of weird; logically it should skip both cases. An inclusive variant that picks an arbitrary case would be lossy, as well. Including both leaves the decision to ignore that case to the user, and I think with the right helpers it'll be plenty ergonomic.

**Comment by sdleffler** [comment]
Looks great! I mean, we know the both case won't happen anyways, so we can just mark it unreachable and honestly that's probably the best thing to do there, since if something does have both components something is very wrong. That was fast!

**Comment by Ralith** [comment]
Great, thanks for the feedback! Let me know if you'd like a formal release sooner rather than later.
