### ISSUE TITLE
Improvement: Add BundleClone and EntityBuilderClone::add_bundle

### ISSUE THREAD

**Issue by ten3roberts** [Ralith/hecs#211]
Currently, there is no add_bundle or alike function to the cloneable entity builder due to the fact that there is no trait for a cloneable bundle of components or similar.

A helper trait similar to Bundle which is auto implemented for tuples that implement clone would enable this behaviour and could be published without breakages.

**Comment by Ralith** [comment]
Released in 0.7.1.
