### ISSUE TITLE
[ macro ] Make hecs-macros::Bundle implement DynamicBundleClone

### ISSUE THREAD

**Issue by ten3roberts** [Ralith/hecs#214]
If a struct implements `Clone` the `Bundle` procedural macro should change behaviour and also implement `DynamicBundleClone`, allowing for seamless usage of bundle structs in cloneable builders. 

This change would not affect `hecs`, only `hecs-macros`

**Comment by ten3roberts** [comment]
In my game engine `ivy`, I have multiple bundlez such as `TransformBundle`, or `RbBundle` that allows initialization of required components with sane defaults, such as adding a scale of 1. This allows me to not having to use Option queries and instead rely on sane defaults if not all fields are specified. It also allows the components to be mutated because they exist. An example of this is a Resitution value for colliders which is often left at default, but could be change without having to check and add it if it doesn't. It exists for all entities also having a velocity etc.

These bundles are all value types with Copy, Clone, PartialEq etc, but as of currently cannot be used with `EntityBuilderClone`.

I do not have much experience with procedural macros, so I do not think I may be able to implement it myself.

**Comment by Ralith** [comment]
A macro cannot judge whether a struct('s field) implements `Clone`, because they run before type-checking. Instead, a new `derive(DynamicBundleClone)` macro should be defined.

**Comment by ten3roberts** [comment]
In that case I can start looking into it. Should `DynamicBundleClone` only implement only DynamicBundleClone or Bundle and DynamicBundle as well?

In my opinion, the first option is better and requiring both `Bundle` and `DynamicBundleClone` derives which ensures implementations won't conflict if both are used. This is similar to the std PartialEq, Eq, and Eq, Hash pairs.

**Comment by Ralith** [comment]
Fixed by #215.
