### ISSUE TITLE
[ Request ] Add remove and despawn for CommandBuffer

### ISSUE THREAD

**Issue by ten3roberts** [Ralith/hecs#216]
The command buffer supports insertion and spawning and is incredibly useful. However, it does not support remove operations or despawning.

Another feature that could be implemented is to allow an arbitrary static closure to be passed, which will take the world as a parameter and execute `on_run`. This would require restructuring the commandbuffer by using an `Operation` enum rather than acting like a builder.

**Comment by Ralith** [comment]
> This would require restructuring the commandbuffer by using an Operation enum rather than acting like a builder.

I'm not sure what you have in mind here. If we add new operations to `CommandBuffer`, we would do so by encoding them in additional `Vec`s without modifying the existing (carefully optimized) functionality.

**Comment by ten3roberts** [comment]
Yes. What I meant by it is that it would require storing remove operations separately in a vector. If the commandbuffer is reused, the allocation can as well be reused. I am thinking of doing a system like this for the hecs-schedule to allow for spawning, despawning, removing, and applying closures to the world after the query has run.

To not duplicate functionality I was wondering if this feature would be better inside hecs since it now already has a commandbuffer.

**Comment by ten3roberts** [comment]
The following behaviour has been implemented in 
https://github.com/ten3roberts/hecs-schedule/blob/main/src/commandbuffer.rs

and published on [crates.io](https://crates.io/crates/hecs-schedule).
