### ISSUE TITLE
get_mut2/query_one2 (or similar functionality?)

### ISSUE THREAD

**Issue by sdleffler** [Ralith/hecs#217]
There are a few cases where it would be very useful to be able to reference multiple distinct entities w/ potentially the same components, at the same time. The only way this is currently possible is through the `get_unchecked` methods, or with a query which is later filtered out or collected into an auxiliary structure. Unless I've missed something?

**Comment by Ralith** [comment]
That's the intended usecase of `get_unchecked`. A `query_one_unchecked` would be a natural extension. I haven't felt motivated to add safe `...2` versions since in the general case you might need more than 2 and the little bit of unsafe there isn't terrible, but it's not a super strong opinion.

**Comment by sdleffler** [comment]
What about `query_one_n<..., const N: usize>(...) -> [...; N]`?

**Comment by Ralith** [comment]
Ooh, cheeky. I'm not sure how I feel about the implied quadratic assert.

**Comment by sdleffler** [comment]
I mean, if you're looking at the general case over the 2-case, it's gonna be quadratic, and it's no worse w/ just 2 used as the parameter in the same function.

**Comment by sdleffler** [comment]
It would also be really useful to have `get_unchecked` for `ColumnMut`.

**Comment by Ralith** [comment]
> if you're looking at the general case over the 2-case, it's gonna be quadratic

Unless the caller can otherwise prove uniqueness, in which case no check would be necessary. My concern is that an inefficient but flexible and safe method will tend to draw people away from the optimal but unsafe approach. Though now that I type that out, that's probably not such a bad thing in most cases...

I suppose I'm game.

> It would also be really useful to have get_unchecked for ColumnMut.

https://github.com/Ralith/hecs/pull/219

**Comment by sdleffler** [comment]
Working at light speed as always :D
