### ISSUE TITLE
Export DynamicBundleClone

### ISSUE THREAD

**Issue by ten3roberts** [Ralith/hecs#221]
Currently, the trait DynamicBundleClone is not exported outside the private `bundle` module. This makes it impossible to use it for generic trait bounds and is very inconvenient.

The trait itself is public, but the module is not, nor is it exported outside the module.

Rust doesn't complain at "leaking private type" since it technically is public, though not accessible

**Comment by adamreichold** [comment]
I think this is already fixed? https://github.com/Ralith/hecs/blob/4840f93f15adcc188da8df13be0a129b1a8a91a5/src/lib.rs#L76

**Comment by Ralith** [comment]
Yep, thanks!
