### ISSUE TITLE
"panicking in constants is unstable" at build time in 0.7.2

### ISSUE THREAD

**Issue by kvark** [Ralith/hecs#229]
Regression from 0.7.1 to 0.7.2. Getting this at build time:
```
error[E0658]: panicking in constants is unstable
   --> /home/kvark/.cargo/registry/src/github.com-1ecc6299db9ec823/hecs-0.7.2/src/entities.rs:510:21
    |
510 |             None => unreachable!(),
    |                     ^^^^^^^^^^^^^^
    |
    = note: see issue #51999 <https://github.com/rust-lang/rust/issues/51999> for more information
    = note: this error originates in the macro `$crate::panic::panic_2015` (in Nightly builds, run with -Z macro-backtrace for more info)

```

**Comment by Ralith** [comment]
This was stabilized in 1.57: https://blog.rust-lang.org/2021/12/02/Rust-1.57.0.html#panic-in-const-contexts.

**Comment by adamreichold** [comment]
Maybe we should add a [`rust-version`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) entry to `Cargo.toml`?

**Comment by Ralith** [comment]
Good idea!

**Comment by kvark** [comment]
Bumping MSRV in a patch version should not be done. Instead, it should be considered a breaking change, since it *will* stop building for some users.
