### ISSUE TITLE
How to implement sorting of components during query?

### ISSUE THREAD

**Issue by cmaughan** [Ralith/hecs#236]
Suppose you have a render component designed to draw objects.  If you wanted to sort them front to back, for example, how would you implement a query that sorted the components on the entities?
Obviously you could implement a secondary sort having retrieved them, but I'm wondering if there is a way to do this more idiomatically?

**Comment by Ralith** [comment]
A separate sort pass is necessary for this pattern, and would likely be faster than anything hecs could provide itself anyway, as such an ordering will tend to change between frames and the data you need to sort (the actual draw operations) is likely to be a subset of the data making up an entity.
