### ISSUE TITLE
Query entities in sorted order

### ISSUE THREAD

**Issue by oskargustafsson** [Ralith/hecs#240]
Is it possible to iterate the results of a query, sorted by e.g. entity id?

My use case is that diffing sorted lists is much faster than diffing unsorted lists, O(n) vs O(n^2).

To elaborate, the game engine that I'm working on uses Hecs to store the game entities, of which some have a Renderable component. Each frame, a sorted list of Renderables is passed to the renderer, which then performs diffing to determine which Renderables have been added, removed or modified, compared to the previous frame. Atm, the list is sorted after being retrieved from Hecs, and that is what I want to avoid.

**Comment by Ralith** [comment]
No, hecs cannot maintain a consistent ordering of entities; this would require compromising the performance of either queries (to access entities in random order) or updates (to shuffle potentially large numbers of components around to maintain order).

For most entity rendering tasks, it is most efficient to prepare fresh, complete lists of entities to render each frame rather than trying to compute minimal diffs; the PCIe bus has a *lot* of bandwidth. Alternatively, you could compute diffs outside of the renderer by having an initially-set dirty flag for each entity, and keeping a list of despawned entities that's reset each frame.

You could also maintain your own sorted entity lists and access components via random access, but I would expect that to be slower than either of the above approaches.

**Comment by oskargustafsson** [comment]
Alright, then I know. Thanks for the suggestions! In the case of my game engine, it has a custom rendering pipeline for path tracing interactive voxel worlds, which requires a lot of support data structures. Rebuilding them from scratch each frame is too computationally heavy for real-time applications. But maybe I can do something smarter with regards to the diffing, as you mention.

Just one more question: Are previously used entity ids guaranteed to be eligible for reuse or can there be permanent "holes" in the total entity ids series?

The reason I'm asking is that if the ids are "sufficiently dense", then a fast (O(n)-ish) way to sort them is to put them all in a list where the entity id is the index, and then traverse the list from beginning to end, ignoring empty slots. This is what I do right now, and it seems to work well, but I would sleep better knowing what the limit of the worst-case performance is.

**Comment by Ralith** [comment]
> Rebuilding [support structures] from scratch each frame is too computationally heavy for real-time applications.

Would it be possible to have separate acceleration structures for only highly dynamic stuff? This is a common tactic for collision detection systems. Or are there too many dynamic entities for that to matter?

> Are previously used entity ids guaranteed to be eligible for reuse or can there be permanent "holes" in the total entity ids series?

`Entity::id`s are reused as much as possible; the worst case scenario is a world containing a single entity with `Entity::id` `n` where `n` is the high watermark of the number of concurrent entities. This behavior is not covered by hecs' API stability guarantees, but I have no reason to believe it is likely to change.

**Comment by oskargustafsson** [comment]
> Would it be possible to have separate acceleration structures for only highly dynamic stuff? ...

Let's just say it's complicated :) In order to keep the GPU path tracer fast and simple, static and dynamic renderables are consolidated into a voxel block tile map (texture) and a world grid (texture) pointing to those tiles. Duplicating those structures for dynamic and static renderables respectively would basically double the already high render time. It would make things a lot simpler though!

> Entity::ids are reused as much as possible; the worst case scenario is a world containing a single entity with Entity::id n where n is the high watermark of the number of concurrent entities. This behavior is not covered by hecs' API stability guarantees, but I have no reason to believe it is likely to change.

Nice, good enough for me.

**Comment by adamreichold** [comment]
> The reason I'm asking is that if the ids are "sufficiently dense", then a fast (O(n)-ish) way to sort them is to put them all in a list where the entity id is the index, and then traverse the list from beginning to end, ignoring empty slots. This is what I do right now, and it seems to work well, but I would sleep better knowing what the limit of the worst-case performance is.

If you are trying this, I would suggest at least comparing this against

> You could also maintain your own sorted entity lists and access components via random access, but I would expect that to be slower than either of the above approaches.

as well, using the recently introduced [`QueryBorrow::view`](https://docs.rs/hecs/latest/hecs/struct.QueryBorrow.html#method.view) or [`QueryMut::view`](https://docs.rs/hecs/latest/hecs/struct.QueryMut.html#method.view) methods.

**Comment by oskargustafsson** [comment]
Thanks for the tip! Right now, this is not a performance bottleneck, but if it ever becomes a problem I will try just that.
