### ISSUE TITLE
`spawn_at` is panicking

### ISSUE THREAD

**Issue by felipellrocha** [Ralith/hecs#264]
When I try running the following code:
```
pub fn rehydrate(&mut self, entity: Entity) {
    if !self.world.contains(entity) {
      self.world.spawn_at(entity, ());
    }
}
```

Rust panics with this message:
`panicked at 'index out of bounds: the len is 64 but the index is 4294967294'`

It still manages to create a few entities before doing so, though:
```
INFO engine/src/application/scene.rs:38 Spawning 0v1
INFO engine/src/application/scene.rs:38 Spawning 1v1
INFO engine/src/application/scene.rs:38 Spawning 2v1
INFO engine/src/application/scene.rs:38 Spawning 3v1
INFO engine/src/application/scene.rs:38 Spawning 5v1
INFO engine/src/application/scene.rs:38 Spawning 7v1
INFO engine/src/application/scene.rs:38 Spawning 9v1
```

**Comment by Ralith** [comment]
The root issue here is that the internal `Entities::get` and `::contains` helpers can return false positives for `Entity` values whose IDs are associated with gaps in the entity population introduced by a `spawn_at` with an ID higher than any previously spawned entity. This leads to knock-on failures in e.g. `insert` with such an `Entity`. We should be able to fix this by checking for the sentinel `u32::MAX` archetype index before judging an `EntityMeta` to be live.
