### ISSUE TITLE
[Help] what would a unique component thingy look like

### ISSUE THREAD

**Issue by maraisr** [Ralith/hecs#279]
Hi 👋 love this!

Quick one; in bevy they have this concept of `resources` which is basically in my mind, just a singleton entity, and each resource is just a component of that entity.

so a `add_resource()` would simply be just inserting into that entity?

is any of that correct, or would you mind helping me with something like it?

**Comment by Ralith** [comment]
Bevy's notion of "resources" exists because its system abstraction interposes itself between your code and any access to your application's state. hecs does not impose any such constraints on how you access state, so when you have data that's not related to a specific entity, you can store it the same way you would in any other rust application, as a field in a struct wherever is convenient.

As a result, hecs applications commonly have something like:
```rust
struct State {
    world: hecs::World,
    score: u32,
    time_remaining: f32,
    // other common state...
}
```

**Comment by maraisr** [comment]
Makes sense, probably very different concepts ya! 

And I guess if I was to need "resources" in my systems, I'd actually need a reference into a hecs world to query, so I'd naturally also have access to that resource as all. 

Or is there some fancy way to proxy my state via a component?

**Comment by Ralith** [comment]
There is no reason to store entity-unrelated data in components. Doing so is needless obfuscation.

**Comment by maraisr** [comment]
makes so much sense, (always does in hindsight) thanks mate!

**Comment by adamreichold** [comment]
I just wanted to add that there can be other reasons to need something like resources even when using an ECS like hecs that does not add any constraint as to how systems should look like: If you are working with a "core model with pluggable submodels" scheme, the actual global state of the simulation is not know until all submodels are initialized and resources (aka type-keyed globals) are a way of having submodels communicate with each other without the core model having to know about it upfront.

Of course, this is definitely much more brittle than just passing reference to properly typed data into the systems. It also is also easy to implement by just using something like `HashMap<TypeId, Box<dyn Ayn>>` and downcasting.

**Comment by maraisr** [comment]
Im not going to lie, I did not understand half of that, But great queues for some research on my part!

In terms of a resource implementation, just did this — works aight.

```rust
pub trait Resource: Any + Send + Sync {}
impl<T> Resource for T where T: Any + Send + Sync {}

#[derive(Default)]
pub struct ResourceManager {
	values: indexmap::IndexMap<TypeId, Box<dyn Any + Send + Sync>>,
}

impl ResourceManager {
	pub fn insert<R: Resource>(&mut self, resource: R) -> usize {
		let (id, _) = self.values.insert_full(TypeId::of::<R>(), Box::new(resource));
		id
	}

	#[inline]
	pub fn get<R: Resource>(&mut self) -> &R {
		let item = self.values.get(&TypeId::of::<R>()).unwrap();
		unsafe { item.downcast_ref_unchecked::<R>() }
	}

	#[inline]
	pub fn get_mut<R: Resource>(&mut self) -> &mut R {
		let item = self.values.get_mut(&TypeId::of::<R>()).unwrap();
		unsafe { item.downcast_mut_unchecked::<R>() }
	}
}
```

---

that being said, would be great to see at least something sample/small about how to potentially solve some of these _not quite in scope_ but _very close_ concepts.

**Comment by Ralith** [comment]
https://crates.io/crates/resources is an of-the-shelf implementation of that for when you really want it, but for people who aren't specifically building dynamic plugin systems I recommend not undermining the type system.

**Comment by maraisr** [comment]
When you say "building a dynamic plugin system" what exactly do you mean? Oh and in case I am building that, (and shouldn't be) do you know of any off the shelf ones?

**Comment by Ralith** [comment]
I'm referring to what Adam described above, where you're combining multiple independently developed subsystems together in unpredictable ways at runtime. There's nothing fundamentally wrong with building that if it's what you really need, but most applications don't need that, and hence can take simpler, faster, and less error-prone approaches.

**Comment by maraisr** [comment]
I'm really just building a light bevy, and no idea what I'm doing 😂 but it's fun. Just trying to say, have an entity in hecs and somehow tell my wgpu renderer, how to draw that entity. 

So my thinking was, a mesh2d "resource" that houses all the shader stuff etc. and exposes a "draw" method then apply a component on the entity annotating it as a mesh2d entity, and boom. During render, suck out all the drawable entities, and run their draw functions from the resource. 

But yo, also no clue 😂

**Comment by Ralith** [comment]
Replace "resource" with "struct" in that paragraph and you're golden.
