### ISSUE TITLE
Removal of `World::get_mut` is not mentioned in the changelog

### ISSUE THREAD

**Issue by PatchMixolydic** [Ralith/hecs#284]
[`World::get_mut`](https://docs.rs/hecs/0.7.7/hecs/struct.World.html#method.get_mut) was removed in hecs 0.8.0, presumably because [`World::get` can now replace it](https://github.com/Ralith/hecs/blob/master/CHANGELOG.md#080). However, this is not explicitly mentioned in the changelog, which can cause confusion during upgrades.

**Comment by Ralith** [comment]
I'd be happy to merge a PR that makes this clearer.
