### ISSUE TITLE
Closure component

### ISSUE THREAD

**Issue by wrnrlr** [Ralith/hecs#292]
I was wondering if it is possible and/or sensible to be able to create a component out of a closure or function.
Something like this:

```
for (_id, (f)) in world.query::<(Box<dyn Fn()->Point>,)>() {
        //...
}
```

This could be a nice way to program some dynamic behaviour without needing a hierarchy of systems and entities.

**Comment by Ralith** [comment]
Any Rust type that satisfies `Send + Sync` may be used as a component. This includes boxed closures that include that constraint.
