### ISSUE TITLE
Column serialize all serializable components

### ISSUE THREAD

**Issue by konceptosociala** [Ralith/hecs#296]
If I want to make save-load implementation for `World` in my game/engine, I would like to save all components I may, which are a part of a scene being saved. But according to docs I can only serialize a limited range of components, which are hardcoded like 
```rust
try_serialize::<Position, _>(archetype, &mut out)?;
try_serialize::<Velocity, _>(archetype, &mut out)?;
```
Is there any approach to make it universal for all serializable components in a `World`?

**Comment by Ralith** [comment]
There's no built in mechanism for that, since there's no graceful way to dynamically check for trait implementations on an arbitrary type in Rust. I recommend solving it at the application layer. You could e.g. use a declarative macro to reduce boilerplate if desired.

**Comment by Ralith** [comment]
> What should I specifiy as T?

The type of your component IDs. In your case, perhaps `&str` or `String`?

> Am I able to use string literals/Strings as ComponentId (e.g. stringify!($comp))?

Yep, any serializable type should work fine. I like to use enums, but strings make it easier to maintain forwards-compatibility, so they're not a bad choice.

**Comment by konceptosociala** [comment]
> > What should I specifiy as T?
> 
> The type of your component IDs. In your case, perhaps `&str` or `String`?
> 
> > Am I able to use string literals/Strings as ComponentId (e.g. stringify!($comp))?
> 
> Yep, any serializable type should work fine. I like to use enums, but strings make it easier to maintain forwards-compatibility, so they're not a bad choice.

I also have thought so, and as saving world was successful, loading it made no error, but the world was just empty
So I considered using String inappropriate

**Comment by Ralith** [comment]
Using `String` for component IDs is probably not the reason that happened.

**Comment by konceptosociala** [comment]
I am sorry, I've just forgotten to serialize Camera, so nothing appears on the screen :)
Everything is working, thx for your job!
