### ISSUE TITLE
CommandBuffer insert/remove ordering is a footgun

### ISSUE THREAD

**Issue by Ralith** [Ralith/hecs#308]
`CommandBuffer` allows deferred execution of component insertion and removal. At present, it executes all insertions first, then all removals. This might not reflect the user's intention after calling e.g. `cmd.remove_one::<T>(); cmd.insert_one::<T>(x);`, which could easily happen if one command buffer is reused across widely separated code, a pattern which is normally desirable to improve resource reuse.

**Comment by LPGhatguy** [comment]
This was fixed in 0.10.4!
