### ISSUE TITLE
ecs_bench integration

### ISSUE THREAD

**Issue by extrawurst** [Ralith/hecs#35]
Would be nice to add hens to ecstatics_bench and see how it holds up against the alternatives: https://github.com/lschmierer/ecs_bench

**Comment by Ralith** [comment]
It looks like that hasn't been updated for a couple years (and running benches on free virtual machines sounds pretty sketchy, at least for close comparisons); I wonder if there's a more modern analog?

**Comment by Ralith** [comment]
@TomGillen was kind enough to fill in fair-looking samples at the suite now living at https://github.com/rust-gamedev/ecs_bench_suite. Should provide good directions to investigate for micro-opts!
