### ISSUE TITLE
!Sync + !Send Component

### ISSUE THREAD

**Issue by Umenokin** [Ralith/hecs#353]
Hi folks

It seems from version 0.16 WGPU on the web is !Sync + !Send while hecs Component is an alias for Sync + Send. In such a case how can someone create a component having !Sync + !Send properties. It is rather Rust newbie question I guess 😅

**Comment by Ralith** [comment]
Typically you'd store those in a table in the side (perhaps a `HashMap` or `Slab`) and only store indexes into that table in the ECS. Alternatively, you could use something like [`SendWrapper`](https://docs.rs/send_wrapper/latest/send_wrapper/struct.SendWrapper.html).

**Comment by Umenokin** [comment]
Thank you, @Ralith !
