### ISSUE TITLE
Query by DynamicBundle

### ISSUE THREAD

**Issue by cjhowedev** [Ralith/hecs#360]
Allow for issuing queries using DynamicBundle. We currently have to use a separate struct with `#[derive(Query)]`. It would be nice if we could query a bundle, for example:

```rs
use hecs::{World};

let mut world = World::new();
let mut target_world = World::new();

#[derive(Bundle, DynamicBundleClone, BundleQuery)]
struct MyBundle {
  integer: i32,
  float: f32,
}

let bundle_to_spawn = MyBundle { integer: 1, float: 2.0 };
let spawned = world.spawn(bundle);

for (entity, bundle) in world.query_mut::<MyBundleQuery>() {
  assert_eq!(entity, spawned);
  assert_eq!(bundle, bundle_to_spawn);
  target_world.spawn(bundle.clone())
}
```

Presumably, `MyBundleQuery` is generated by the `#[derive(BundleQuery)]`. This is necessary because each field needs to be wrapped in a reference to work as a query type, so we can't use the original `MyBundle`.

**Comment by cjhowedev** [comment]
After some thought, this is externally implementable. Nevermind

**Comment by Ralith** [comment]
This has come up a few times before. The tricky part is that you might reasonably want either shared or unique references for each component of a bundle, so a clean general-purpose solution becomes complex. You could bodge something ugly but serviceable pretty easy with a declarative macro though, yeah.

**Comment by Ralith** [comment]
If your goal is actually just to do some `assert`s like that, you might be interested in https://github.com/Ralith/hecs/pull/354.
