### ISSUE TITLE
WASM / Parallelism in WASM support?

### ISSUE THREAD

**Issue by Wandalen** [Ralith/hecs#374]
Hello. Thank you for this wonderful open-source project. Will I encounter any difficulties using `hecs` in a `WASM` environment, specifically regarding browser parallelism?

**Comment by Ralith** [comment]
hecs is `no_std`, so it should work fine in wasm. AFAIK sharing data between theads in wasm is difficult, but I'm not an expert. Feel free to open an issue if you find something specific missing.
