### ISSUE TITLE
Query slice of entities the most efficient way

### ISSUE THREAD

**Issue by kaphula** [Ralith/hecs#378]
Hello, 

Is there a dedicated way of querying a slice of entities for a set of components instead of iterating over all of the components or using get?

Something like this:
```rust
            let list = vec![]; // list of entities
            for (e, (a, b)) in world.query_mut_list::<(&A, &B)>(&list) {

            }
```

Or should I just iterate over every entity and use `world.get` or is that discouraged due to performance reasons? In bevy there is a separate function for this `query.iter_many(list)`.

**Comment by adamreichold** [comment]
You can use views for efficient random access by entity ID, amortizing the setup cost of `World::get`, for example via [`QueryBorrow::view`](https://docs.rs/hecs/latest/hecs/struct.QueryBorrow.html#method.view).

**Comment by kaphula** [comment]
Like this?

```rust

let list = vec![]; // list of entities
let view = world.view_mut::<(&A, &B)>();
for x in list {
   if let Some((a, b)) = view.get(x) {
      
   }
}
```

**Comment by adamreichold** [comment]
> Like this?

Yes.

> Btw, what is the best way to store PreparedQuery values in your program? Why would you ever use anything else than prepared query if it is the fastest way to perform component queries. Ideally you could store these in global space like structs and use them as needed. Is this possible?

Well, I'd say you would use direct queries if you are unprepared/unwilling to store prepared queries somewhere. Especially for queries which are executed rarely, it might not make sense to pay the space overhead of prepared queries. And it is additional complexity in any case which can often be more problematic than the lost of performance.

Personally, when writing simulations, I put the prepared queries into the "systems" which use them, where usually other auxiliary data structures like indexes and buffers already exist. For example, I often also need to collect lists of entities and I also put those `Vec` into the systems to reuse the underlying allocation between time steps.

**Comment by kaphula** [comment]
Sorry, I did not quite get what you mean by putting prepared queries into the systems. Since systems are just functions, the prepared queries cannot live inside the systems across frames without getting reconstructed every time the system is executed? I agree that complexity is a good point, and actually the reason why I am in the progress of switching to hecs from bevy.

**Comment by adamreichold** [comment]
> Since systems are just functions, the prepared queries cannot live inside the systems across frames without getting reconstructed every time the system is executed?

As hecs itself does not mandate any system structure, this is not necessarily so. And in my case, we usually end up creating system structs with a "run" method or something like that. These structs do not store model state, but technical state, i.e. auxiliary data structures like indexes, buffers or prepared queries.

**Comment by kaphula** [comment]
I see. That sounds a bit unergonomic to me. I was hoping for something more straight forward like throwing the prepared query into the global space as static and wrapped in `OnceCell` but I could not get that to work.

I guess it is not too bad if you do something like this:

```rust
pub struct Game2<'a> {
   pub world: hecs::World,
   pub ctx: GameContext,
   pub prepared_queries: HecsPreparedQueries<'a>,
}


pub struct HecsPreparedQueries<'a> {
   q: PreparedQuery<(&'a StaticCameraCullableECS)>
}
```

But I am not very happy about the life time pollution it forces me to do.

**Comment by adamreichold** [comment]
> But I am not very happy about the life time pollution it forces me to do.

You can store the prepared queries using only `'static` lifetimes. The types only define the queries and the actual short-lived lifetimes of returned references are rebound by the fetch implementation.

**Comment by kaphula** [comment]
Oh perfect. I guess that answers all of my questions for now. Thanks for your time and the tips!
