### ISSUE TITLE
Example for serializing, deserializing and using the `SerializeContext`?

### ISSUE THREAD

**Issue by kaphula** [Ralith/hecs#380]
Hey, 

Do we have any working examples for demonstrating de/serialization in the context of saving world to disk and loading it back?

**Comment by Ralith** [comment]
There are no examples beyond the rustdoc, which should cover the specifically tricky parts. I'm open to merging a clean, commented end-to-end example, if you like.

**Comment by Ralith** [comment]
Sounds like you understand it fine to me. Did you have trouble doing that?

**Comment by kaphula** [comment]
Alright, thanks! I did not try it yet because I did not want to waste time implementing something I did not understand.
