### ISSUE TITLE
`world.view` causes `world.get` to panic even if the view is never used

### ISSUE THREAD

**Issue by kaphula** [Ralith/hecs#382]
Consider the following example:

```rust
      struct CompA {};
      struct CompB {
         reference_to_a: hecs::Entity
      };
      let mut world = hecs::World::new();
      let a_entity = world.spawn((CompA {},));
      world.spawn((CompB { reference_to_a: a_entity },));
      let mut comp_a_view = world.view::<(&mut CompA)>();
      fn nested_function(
         world: &hecs::World,
         b: &mut CompB
      ) {
         let aref = b.reference_to_a;
         let Ok(a) = world.get::<&mut CompA>(aref) else { // <- panics with: "CompA already borrowed"
            return;
         };
         // do something with a...
      }
      for (e, b) in &mut world.query::<(&mut CompB)>() {
         nested_function(&world, b)
      }
```

This causes panic even though `comp_a_view` has not been used to borrow components from the world for actual usage. Is there a reason why this should not be allowed if we consider the Rust borrowing rules?

This is a pretty scary footgun since often it can be useful and ergonomic to declare multiple views on a higher level when we consider the function call stack. On a high level, you can create many queries that make use of the same `view` that lives in the same scope as the queries. Then, inside the queries' scope, helper functions are called that can go very deep in the function call stack. If one of these helper functions accidentally access a component that is being held by a `view`, you get a panic. It is an easy mistake to make in a complex scenario because you only see it during runtime when one of these helper functions happen to violate this rule. 

In this example, the `comp_a_view` is used in two queries to compute some data, then it is never used again. However, when we access `CompA` in the following query which is unrelated to `comp_a_view` (`comp_a_view` is never used again after this point) we still get a panic:
```rust
      struct CompA {
         data: usize
      };
      struct CompB {
         reference_to_a: hecs::Entity
      };
      let mut world = hecs::World::new();
      let a_entity = world.spawn((CompA { data: 0 },));
      world.spawn((CompB { reference_to_a: a_entity },));

      fn nested_function(
         world: &hecs::World,
         b: &mut CompB
      ) {
         let aref = b.reference_to_a;
         let Ok(a) = world.get::<&mut CompA>(aref) else { // <- panics with: "CompA already borrowed"
            return;
         };
         // do something with a...
      }

      let mut comp_a_view = world.view::<(&mut CompA)>();
      for (e, a) in comp_a_view.iter_mut() {
         a.data += 1
      }
      for (e, a) in comp_a_view.iter_mut() {
         a.data += 2
      }

      for (e, b) in &mut world.query::<(&mut CompB)>() {
         nested_function(&world, b)
      }
```

**Comment by Ralith** [comment]
This is intended behavior. A view is a borrow of all components that it exposes. It is therefore usually a bad idea to have a bunch of views that you keep around just in case. Instead, create views directly when and where they are needed, and drop them afterwards, like any other borrow.

If you only want to borrow for the duration of access to an individual component, use `World::get` instead of views. That's what it's for. Views exist expressly to avoid the extra overhead this incurs by doing all the borrows once, up front. It is not even possible to borrow in `View::get`, because it doesn't return a smart pointer as would be necessary to know when it's safe to release a borrow.

If this was unclear, documentation PRs would be welcome!

**Comment by Ralith** [comment]
Added a note to clarify this in 0e12d7ffee12b279ae98422e7c8d774d6ce0c063.
