### ISSUE TITLE
Referenced components

### ISSUE THREAD

**Issue by ottworks** [Ralith/hecs#46]
I'd like to load a Model once, then store it and have my entities reference it. When I try to use a &Model as a component, the compiler says that it needs a static lifetime. Is there a reason for this limitation and a way to get around it?

**Comment by Extrawurst** [comment]
Not storing references to the components is the idea of an ECS. ECS libs like hecs are designed to support a fast lookup of components that belong to your entity so that you don't need to store them as references

**Comment by Ratysz** [comment]
My usual solution is adding a layer of indirection: store your `Model`s in some sort of keyed collection (a `HashMap` is common), and use the keys as components. An alternative solution is to use `Arc<Model>`, rather than plain references.

**Comment by Ralith** [comment]
Thank you everyone for weighing in! I personally favor the approach @Ratysz described with a [`slab`](https://crates.io/crates/slab) or similar.

In general rust makes it difficult to do dynamic typing for values with non-`'static` lifetimes, so while it's possible to imagine an ECS world that contains short-lived data, one that internally relies on downcasting would be difficult to implement. There are incidental advantages to having a layer of indirection, including easy support for asynchronously loaded and hot-reloaded assets, so it isn't usually judged a significant issue.
