### ISSUE TITLE
get multiple components

### ISSUE THREAD

**Issue by Extrawurst** [Ralith/hecs#50]
is there a way to `world.get` multiple components of an entity? to not pay the entity.get cost multiple times?

**Comment by Ralith** [comment]
It's unlikely to matter for performance in practice, but [`World::entity`](https://docs.rs/hecs/0.2.7/hecs/struct.World.html#method.entity) provides that.

**Comment by Extrawurst** [comment]
I see! Thanks for the hint at `World::entity`!
