### ISSUE TITLE
AtomicBorrow race condition

### ISSUE THREAD

**Issue by omni-viral** [Ralith/hecs#53]
In `src/borrow.rs` functions `AtomicBorrow::borrow` and `AtomicBorrow::release_mut` conflict with each other.

This execution order will break internal state

Atomic value is `0` originally.
Thread #1 `AtomicBorrow::borrow_mut()` stores `UNIQUE_BIT` in atomic value.
Thread #2 `AtomicBorrow::borrow()` increments atomic value. Sees `UNIQUE_BIT` set
Thread #1 `AtomicBorrow::release_mut()` stores `0` in atomic value.
Thread #2 `AtomicBorrow::borrow()` decrements atomic value.
Atomic value is `usize::MAX`.

**Comment by omni-viral** [comment]
Solution:
Rewrite `AtomicBorrow::release_mut()` implplementation as
```
let value = self.0.fetch_and(!UNIQUE_BIT, Ordering::Release);
debug_assert_ne!(value & UNIQUE_BIT, 0);
```

**Comment by Ralith** [comment]
Thanks for finding this!
