### ISSUE TITLE
BatchedIter is undocumented

### ISSUE THREAD

**Issue by Nemo157** [Ralith/hecs#59]
[`QueryBorrow::iter_batched`](https://docs.rs/hecs/0.2.9/hecs/struct.QueryBorrow.html#method.iter_batched) returns a `BatchedIter` which does not link to any documentation.

**Comment by Nemo157** [comment]
Looks like the issue is that `BatchedIter` is not publicly accessible anywhere, it's a `pub` type within a private module and needs re-exporting.

**Comment by Ralith** [comment]
Good catch, thanks! That's bitten me a few times now...

**Comment by Ralith** [comment]
Fixed in 552548986902995e87edbb108dc9aaa90dc85b65, released as 0.2.10.
