### ISSUE TITLE
Consider adding an example in readme.md

### ISSUE THREAD

**Issue by ducaale** [Ralith/hecs#67]
I love the minimalist approach which hecs takes and I believe many people will do. I think adding a brief example in `readme.md` would help more people discover the library. [specs](https://github.com/amethyst/specs) and [legion](https://github.com/TomGillen/legion) which are mentioned in `other libraries` section already do this. I believe the snippet in https://docs.rs/hecs/0.2.12/hecs/ is a good candidate for inclusion in `readme.md`.

**Comment by Ralith** [comment]
Thanks for the issue! Others have made similar comments, so I think you're right. Opened #68 to resolve this.
